### ISSUE TITLE
Valid variable characters

### ISSUE THREAD

**Issue by henrytseng** [Gigzolo/dataobject-parser#2]
Open to suggestion on this issue because we're still on the fence.  Not sure what should happen but obviously there's a collision between valid variable characters and characters you can use as valid names according to an Object's available name-value pairs.

**Comment by siacomuzzi** [comment]
The `|` char is used to split. For example:

Input: `{ 'metadata.foo|bar': 'some-text' }`
Current Output:

```
{
  metadata: {
    foo: {
      bar: 'some-text'
    }
  }
}
```

I think should be:

```
{
  metadata: {
    'foo|bar': 'some-text'
  }
}
```

**Comment by henrytseng** [comment]
I think the syntax that we're using here is a bit awkward.  It's likely that the syntax should be updated to avoid the use of | (pipes) and - (dashes) in object names.

**Comment by henrytseng** [comment]
I've made the requested update for now.  (e.g. - it's likely that other special characters should be added if this convention is used)

**Comment by siacomuzzi** [comment]
thanks man!
