### ISSUE TITLE
Please update to latest lodash

### ISSUE THREAD

**Issue by blord-fullscreen** [Gigzolo/dataobject-parser#8]
For browser apps, size matters. For webpack and similar workflows, requiring ancient versions of utility libraries runs a risk of code duplication in bundles. lodash is currently at 4.17.4. You're specifying "~2.4.1".

While I'm here wishing, could you also please require only the utility functions that you're actually using, and <a href="https://twitter.com/dan_abramov/status/605691126549508096?lang=en">not the whole library</a>? At a glance, it looks like you're only calling `isArray`, `isObject`, and `isUndefined`. Again, it's lighter on the wire.

Thanks for maintaining this!

**Comment by henrytseng** [comment]
Sorry this is an ancient project.  I think it'd be a good idea to not use those.

**Comment by blord-fullscreen** [comment]
I'm not sure what you mean. It was version-bumped just three months ago.

**Comment by henrytseng** [comment]
The code was written 3 years ago, not used internally anymore.  I'll update it to remove lodash--that sounds reasonable.  Hope it continues to be helpful to you if you need it.

**Comment by blord-fullscreen** [comment]
Yeah, I'm using it. Thanks!
